language: go
go:
  - 1.12.4

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - GO111MODULE=on
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=diun
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=diun
    - secure: rn4yR3+WxNN+XAjHqq91GYcimHYMac4Z14zkrPkjD1HiSap8lkEyEzpVFIHAKcRxUauurSD3InB+CYKNXnFNy8l25vYTGsJE4v5gcYeM7xLAArFXAX/fgJte3X5Y985KA8LEj2iL23eKQP/stdHz7Q6532fKNAWpIn/AXMPCcq/OfgTL/IDvub0CdQ+ujB/r4fge45V/ayUcwGybXSfCE9sgfpejF53i1BB4KUTXsTpANuaiQ4P7T2MhFlAZm7PKERZrBqDZ96naGfGMUMbnOVg1G7vixRvicKYrEYfCcY3ynyH7fOAXBUlcRul7k+AnuMCzCzqHfwl79v4vvDRPbKiQW+M3AesTxH20URaJEgopN5AVlN9hgziV9Btcy57QPWuSPq5vJuR359QOu9xQCVzto7y0xCJiynZf8ekWRu6DVUvI9RomFZLNioK2U8nHcCuadkGI2cYSnv9NxnAuvUrdzZhTDeD9OkbYM6r9pjk2UwoxwD/IJOqcHICynOUeZa7zd/HvO+HgEuRalcEwAXfALlljKJWedAJRtQ2GIHAO7I17Y20zipbYR94iJoNc5m5ED60eKGFkVhPPeE3n46D3rex6fl8KVVMexK0QTEenBOgnWW8VJcKCkLvSJ5kvIQlgFBSw2qCCLBSZ84fPgVPCWSOLnTF5/Sh4azyA3yI= # DOCKER_PASSWORD
    - secure: KpHMIy36vZDVf9/cOg7USbQmlEjBlz7+PuIC1P2jPSMo1yp+hAhPbqZwQBh3FZXCtaFbaZEVnnm+4jnKgPirWgqFsMLcP3v4KcP5AW70wVn4fymWeveeDRSnAmgaXhJxxzZJaB6Ps+B9ULtZ8vymrJt9vsiaJ6CO79BeCoQZsTJulSiKlNVgZSMGHfylTt/RAGfWJoLAnS9ROFPpOShXyuSjNzxBopOngWsUxvgQIm3U4qg33DqBcxrrxrKwYIAY9NKCh5yLAohVDzZ+iew/bNmQ/8vqfQQlk4773RYKYa5CtTuHhW/a+Vxsk0CBY5Pu4aZBF2uRFal1IiWiwnFA8GgMeCLAea9uu2vOOqQ2nr/N+GVRP9hMLb7lsEO1eUu1951YgbsUy7naPSdT75aW+6XGbRfFMCx1uCDwK7D3VhY5unUSwn1M0E+jexTbkd1dxy5STUPp3kkh3CvD9W3meGN/ASW+Ky79wjOoVyUOwx7i7jRKHP2ZFOQQvV6Ce/Nb1qNJcul60QpS8Me3XbbQn0GbaHEJvYyNjDDMKJ8vQQJTEIJHiUA2m6a11QmSN00qH6NFM17z60LEnOErNiD3oyBErm2JE4cgClpn3DCtF7FqPA/tjzfiDnVSO/rzvEJ9W/34/lmS1BYlStJuEltPcbpmPUDYsqvAwP0MMWZEgvw= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

install:
  - curl -sL https://git.io/goreleaser | head -n -2 | bash
  - tar -xf /tmp/goreleaser.tar.gz -C $GOPATH/bin
  - goreleaser -v

script: ./build.sh

deploy:
  provider: releases
  api_key:
    secure: NkexB33JizM5kiqqxS7qo5xk6vsKp5+jRQT/gpSVt91XBrzOEnTksVdeoIFoJJ5pFfZfmDyV3e7MsGM9hnf6HUe6NKiSpOAjN7egTs3PqfwxOynFG8IyOIrUO6Q8EceVfl3/UeSH2hr86SUkO8tCsI4g7wTlnoIjsqNs0o5MAX24e2TAr9aFpoTAbDMOijE5Oqjgm/dIAik/N2MS+v8kqZP/KRx8/4hcUUhV5jt0D7LyxjqK3uAZN7bg4e3rltEMnfvKJJ/2s1RnJYzT9GqrATTL6CVZZisspFMgUjBT0y8fsiqqCQVAU/XoftiDIoJm1QOricDchqy7MrGTDjmR+IfVvEqlkp/bWaCEJURRESpsqnFU1g6ega1hpllGQsSCzymTA1SGs0ArUurSQY8S4anz3SiZI4mNusCIXO8w1rrAOXJya++6dTDws8svcPzuYbL7F1/Wh2ejyl9po9p8D69YPv3eVTMDjOQC/2PMNfQuTHku3ozToyvIG4hEHIudpTFvcn2IJXlMeYGoc08fAXSR95SFUVpUUgIsrGwCArw4fi7S5qBT27Dux2HDtGCtR8rqMrqxjHy2aME0oFsVq+tXvMkoDYXukMA50QHBuoMHhBGwzXMXj7ujW/eyLShu1hGikFSgiSTeX+Nnw/lixnsRClsf748CjdkJ86DPciw=
  file_glob: true
  file:
    - dist/checksums.txt
    - dist/*.tar.gz
    - dist/*.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true
