db:
  path: diun.db

watch:
  workers: 100
  schedule: "*/30 * * * * *"
  os: linux
  arch: amd64

notif:
  mail:
    enable: false
    host: localhost
    port: 25
    ssl: false
    insecure_skip_verify: false
    username:
    password:
    from:
    to:
  webhook:
    enable: false
    endpoint: http://webhook.foo.com/sd54qad89azd5a
    method: GET
    headers:
      Content-Type: application/json
      Authorization: Token123456
    timeout: 10

regopts:
  someregopts:
    timeout: 5
  bintrayoptions:
    username: foo
    password: bar

image:
  - name: docker.io/crazymax/nextcloud:latest
    regopts_id: someregopts
  - name: crazymax/swarm-cronjob
    watch_repo: true
    include_tags:
      - ^1\.2\..*
  - name: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:4.0.0
    regopts_id: bintrayoptions
  - name: docker.bintray.io/jfrog/xray-server:2.8.6
    watch_repo: true
    max_tags: 50
  - name: quay.io/coreos/hyperkube
  - name: docker.io/portainer/portainer
    watch_repo: true
    max_tags: 10
    include_tags:
      - ^(0|[1-9]\d*)\..*
  - name: traefik
    watch_repo: true
  - name: docker.io/graylog/graylog:3.2.0
  - name: jacobalberty/unifi:5.9
  - name: quay.io/coreos/hyperkube:v1.1.7-coreos.1
  - name: crazymax/ddns-route53
    watch_repo: true
    include_tags:
      - ^1\..*
